### ISSUE TITLE
Is there cortexm0-llvm?

### ISSUE THREAD

**Issue by chlizheng** [martinribelotta/cortex-m-llvm#3]
Hi.
Does this just support cm3/cm4? Can it be changed to support cm0?
best regards.

**Comment by martinribelotta** [comment]
The only issue in armv6m (cortex-m0) support is the movt/movw emition of thunks:
https://reviews.llvm.org/D36823
https://en.wikipedia.org/wiki/Thunk

In my experience, the clang not generate thunks with movt/movw in any cases, but the warning is on by default. This may vary in next lld releases (arm-none-eabi-ld not show this warning)

I put the relevant config files to work with m0/m0+ in few hours. Try to compile your code and test the results

**Comment by chlizheng** [comment]
Thanks. What this project do is to translate llvm-ir to cortex-m3/m4, and now it can already translate llvm-ir to cm0. Is that right?
My biggest uncertainty is whether llvm-ir can be translated  to cm0 in the backend section?

**Comment by chlizheng** [comment]
Hi.
And when I build llvm toolchain. I use "make install" to install llvm/clang/lld, but there are some errors as"Makefile:33 Makefile.config:No such file or directory
     Makefile.rules:No such file or directory
   make: *** No rule to make target '/Makefile.rules' "
Do you encount this before and how should I resolve it?
Thanks.

**Comment by chlizheng** [comment]
Hi.
And when I build llvm toolchain. I use "make install" to install llvm/clang/lld, but there are some errors as"Makefile:33 Makefile.config:No such file or directory
Makefile.rules:No such file or directory
make: *** No rule to make target '/Makefile.rules' "
Do you encount this before and how should I resolve it?
Thanks.

**Comment by martinribelotta** [comment]
@chlizheng The most easy way to obtain a working llvm/clang is install the last binary version from:
http://releases.llvm.org/download.html
(in section **Pre-Built Binaries:**)

This project is only a Makefile and startup process for cortex-m using clang/llvm instread of gcc toolchains. The real magic is from LLVM project:
https://github.com/llvm-mirror/llvm

Specifically in the LLC tool, based in MC/Target of LLVM libraries:
https://github.com/llvm-mirror/llvm/tree/master/lib/Target

The cortex-m0 and all armv6 in thumb(1) mode is supported for many years ago and is very well tested.

The compilation process is:
  - clang frontend compile c code to llvm-ir
  - LLC translate this to architecture specific assembler
  - LLVM-MC get the assembler generated by LLC and translate to binary object format (*.o)
  - LLD link objects and libraries with the memory layout described in linker script (*.ld) and produce the final ELF object
  - Additionally, the llvm-objcopy is used for translate ELF to raw binary file suitable for programming the flash of processor directly (put entirely in the flash using whatever method) and llvm-objdump disassemble the final ELF in human readable ASM syntax (*.lst files)

**Comment by chlizheng** [comment]
Thanks.
