### ISSUE TITLE
Can one assembly instruction be transformed to llvm-ir?

### ISSUE THREAD

**Issue by chlizheng** [martinribelotta/cortex-m-llvm#4]
Hi.
Now I want to transform some other assembly instrcutions rather than high level language to llvm-ir such as stm8, cortexm0 instrctions and so on. Do you know whether it's feasible? And  am I  just need learn the instruction section of llvm-ir reference to do this job?
best regards.

**Comment by martinribelotta** [comment]
If I understand, you are looking to convert assembler (or machine code) on a specific architecture to llvm like a decompile process (but most feacible in machine code to machine code)

In teory, is pefectly factible to translate assembler1 to IR and IR to assembler-N. LLVM can do this but not out-of-the box.

A fast search on google show me this:
https://stackoverflow.com/questions/4636498/recompile-a-x86-code-with-llvm-to-some-faster-one-x86/4636583#4636583

http://dagger.repzret.org/

https://github.com/trailofbits/mcsema

https://code.google.com/archive/p/llvm-qemu/

The most near tool to your needs is the qemu on-the-fly machine code to machine code translation but this is in experimetnal stage and is just-in-time tool (if I understand, you found ahead-on-time tool)

Your project is interesting but excess the scope of this repository and I do not plan to support that posibility. If you make progress with it, I encourage you to publish the results in open-source manner
